### ISSUE TITLE
Crash when Connection response is not of type NSHTTPURLResponse

### ISSUE THREAD

**Issue by dkk** [robertmryan/download-manager#1]
Sometimes, for example when downloading files from FTP, the function connection:didReceiveResponse: will contain a response of type NSURLResponse and not of type NSURLHTTPResponse, causing a crash.

SOLUTION: (This ignores didReceiveResponse when the response is not of type NSHTTPURLResponse)

Change the code of Download.m/connection:didReceiveResponse:
to

```
- (void)connection:(NSURLConnection*)connection didReceiveResponse:(NSURLResponse*) response
{
    if ([response isKindOfClass:[NSHTTPURLResponse class]]) {
        NSInteger statusCode = [((NSHTTPURLResponse *)response) statusCode];
        if (statusCode == 200)
        {
            self.expectedContentLength = [response expectedContentLength];
        }
        else if (statusCode >= 400)
        {
            self.error = [NSError errorWithDomain:[NSBundle mainBundle].bundleIdentifier
                                             code:statusCode
                                         userInfo:@{
                          @"message" : @"bad HTTP response status code",
                          @"function": @(__FUNCTION__),
                          @"NSHTTPURLResponse" : response
                          }];
            [self cleanupConnectionSuccessful:NO];
        }
    }
}
```

**Comment by robertmryan** [comment]
Excellent. Agreed. I've also updated this to make sure that it set `expectedContentLength` to -1 if not a `NSHTTPURLResponse` (as negative values designate no `expectedContentLength` provided).

Thank you for bringing that to my attention. I focus on HTTP downloads all the time, so I neglected FTP downloads.
