### ISSUE TITLE
Use without interface builder.

### ISSUE THREAD

**Issue by ghost** [robertmryan/download-manager#3]
I was wondering how difficult it would be to get this working without the use of storyboards or xibs.

I have it merged into my project, however the buttons aren't showing up.

Also how would I change the NSArray *urlStrings, to use any file I tap?

Thanks.

**Comment by robertmryan** [comment]
> I was wondering how difficult it would be to get this working without the use of storyboards or xibs.

Technically, there is no reason you couldn't develop the UI programmatically. It seems like a lot more work and harder to maintain, for little discernible benefit, but to each his own.

> I have it merged into my project, however the buttons aren't showing up.

There's only one button in my sample project, the "cancel" button on the toolbar. I'm not understanding to which buttons you refer.

If you're talking about buttons in your existing project, it might be a question of how you "merged" these projects. If you tried to add your code to my project, I could imagine all sorts of issues. I'd be inclined to go the other way, to just add my `Download` and `DownloadManager` classes to your existing project, and then just write the code in your project to use these classes. That way, your existing UI should be unaffected.

> Also how would I change the NSArray *urlStrings, to use any file I tap?

There's no reason you need `urlStrings` array. I only have it there for demonstration purposes.

Assuming (a) you've already instantiated your `DownloadManager`; (b) you know the full path of where you want to save the file (`localFilePath`); and (c) you know the url of the file being downloaded (`remoteURL`), to start a download with a tap is as simple as:

```
[self.downloadManager addDownloadWithFilename:localFilePath URL:remoteURL];
[self.downloadManager start];
```

Your app obviously needs to be able to present the UI of list of files available for download and call the above code when the user taps on one, but it doesn't seem like there's anything there which is fundamentally that challenging.

**Comment by ghost** [comment]
Bare with me as I'm still quite new to this depth of coding, but yes the button I was referring to was the cancel button.

Good to know about the strings, as I can just remove that part.

How would I code these elements without IB?

```
@property (weak, nonatomic) IBOutlet UIActivityIndicatorView *activityIndicator;
@property (weak, nonatomic) IBOutlet UILabel *filenameLabel;
@property (weak, nonatomic) IBOutlet UIProgressView *progressView;
```

**Comment by robertmryan** [comment]
There are two approaches:
1. You could just add these three controls to your `cellForRowAtIndexPath` method as described in [Programmatically Adding Subviews to a Cell’s Content View](http://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TableView_iPhone/TableViewCells/TableViewCells.html#//apple_ref/doc/uid/TP40007451-CH7-SW15) of the _Table View Programming Guide for iOS._
2. An even more elegant (but even more complicated if doing programmatically), you could define a `UITableViewCell` subclass. If you google "[UITableViewCell subclass programmatically](https://www.google.com/search?q=uitableviewcell+subclass+programmatically&ie=UTF-8&oe=UTF-8)", you'll see some relevant links.

If you do it this way, you'll also have to manually define the `frame` for each of these.

Certainly feel free to do this programmatically, but once you do a complex custom tableview cell like this programmatically, you'll start to appreciate why we love the cell prototypes in storyboards so much. What I can do in minutes on a cell prototype in a storyboard, will take you at least an hour or two when doing it programmatically. I don't want to dissuade you (as this exercise you're about to go through will teach you a lot about table view cells), but you may end up reconsidering do it programmatically in the future.

Good luck and happy coding!

**Comment by robertmryan** [comment]
And by the way, regarding adding the cancel button programmatically, in your `viewDidLoad` (or your `loadView`, if doing programmatically), you can add the lines (assuming you are using a `UINavigationController`):

```
UIBarButtonItem *cancelButton = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel
                                                                              target:self
                                                                              action:@selector(didTouchUpInsideCancelButton:)];
[self.navigationItem setRightBarButtonItem:cancelButton];
```

Clearly, you'd also need to define `didTouchUpInsideCancelButton`:

```
- (void)didTouchUpInsideCancelButton:(id)sender
{
    NSLog(@"%s", __FUNCTION__);

    // e.g., you might do

    [self.downloadManager cancelAll];
}
```
