### ISSUE TITLE
Pause and resume the download individual ?

### ISSUE THREAD

**Issue by dangluan** [robertmryan/download-manager#5]
can you add pause and resume the download individual ?

**Comment by robertmryan** [comment]
@dangluan  No, I didn't put in any pause functionality. Cancel, but not pause.

**Comment by dangluan** [comment]
I mean that you can improve your download manager , add pause and continue button to  download file

**Comment by robertmryan** [comment]
@dangluan I must confess that I have no intentions to pursue this at this point. It's not standard `NSURLConnection` functionality provided out of the box, so it's a non-trivial request, and frankly I now generally use `NSOperation`-based solutions like [my download operation class](https://github.com/robertmryan/download-operation) class or frameworks like [AFNetworking](https://github.com/AFNetworking/AFNetworking). 

If you really need suspend functionality, you might consider refactoring this to take advantage of the new iOS7 and Mac OS 10.9 `NSURLSession` functionality, whereby `NSURLSessionTask` appears to offer suspend capabilities. But, sadly, that's not something I'm going to pursue right now, but may take a look at it in the future. 

Thanks for the suggestion!
